import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FavoritesProvider } from "../context/Favorites"; 
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app for Authrs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FavoritesProvider>
          <nav className="p-4 bg-gray-100 flex gap-6 border-b">
            <Link href="/authors" className="text-blue-600 hover:underline">
              Autores
            </Link>
            <Link href="/favoritos" className="text-blue-600 hover:underline">
              Favoritos
            </Link>
          </nav>
          <div className="p-6">{children}</div>
        </FavoritesProvider>
      </body>
    </html>
  );
}
